### ISSUE TITLE
Multithreaded RX

### ISSUE THREAD

**Issue by GIC-de** [rtbrick/bngblaster#106]
This issue tracks all changes related to support multithreaded packet receive (RX) in order to increase scaling.

**Comment by kowsarbd** [comment]
Hello am new in here ... i would like to test BNG blaster can anybody give me detail how to?

**Comment by GIC-de** [comment]
> Hello am new in here ... i would like to test BNG blaster can anybody give me detail how to?
Hi @kowsarbd, 

best way is to start by going trough the quickstart guide. This works on any Ubuntu machine without need to have network equipment for testing. I would recommend to setup a  Ubuntu VM and go trough the this guide set by step. 

https://rtbrick.github.io/bngblaster/quickstart.html
