### ISSUE TITLE
Any Sessions(PPPoE, L2BSA,IPoE, L2TP, ISIS, BGP) Uptime to be exposed 

### ISSUE THREAD

**Issue by DharmendraShetty** [rtbrick/bngblaster#110]
Description:
**************
Any sessions bring up that we do using blaster, it can be pppoe/ipoe/l2bsa/l2tp/isis/bgp sessions.
We dont expose the session uptime in mins/hours. 

Expectation:
**************
A snapshot of the l2bsa(pppoe) 8K sessions are up from 4hours if we manually see. But we need to expose this in blaster on from how long the sessions are up.
NOTE: Snapshot is attached. 

It would be good to expose the session uptime for all the protocols we support...!!
![L2BSA_PPPoE_SessionsUptimeRequest](https://user-images.githubusercontent.com/58907955/192289650-c3539924-d980-4fca-96a5-64a6b16801cf.jpeg)

Thanks,
Dharmendra

**Comment by GIC-de** [comment]
Fixed with version 0.8.1!
