### ISSUE TITLE
More flexibility for the 'access-line' configuration option

### ISSUE THREAD

**Issue by aleheux-tc** [rtbrick/bngblaster#126]
Description:

The way we use BNGBlaster, there is no other device that could insert Option18/38 or Option82 information. The 'access-line' option allows _some_ formatting of the circuit-id / remote-id, but a few more options would help us out a lot.

Our remote-id / circuit-id looks like this:

ps426:62-1102

The 'ps426:' part can be statically defined.
The 62-1102 part is: {outer-vlan}:{inner-vlan}

The reason we would like to be able to test with these values is that our DHCP servers parse these and may assign from different pools, etc.

Desired solution:

In addition to be able to configure this:

        "agent-remote-id": "bngblaster-lab.LAB-A-12345:{session-global}",

Allow something like this:

        "agent-remote-id": "ps436:{outer-vlan}-{inner-vlan},

**Comment by GIC-de** [comment]
Fixed in version 0.8.6!
