### ISSUE TITLE
Service-name should be present in PADR

### ISSUE THREAD

**Issue by DmitriyEshenko** [rtbrick/bngblaster#13]
**Describe the bug**

PPPoE Servers should check existing Service-name in PARD packed as described in https://tools.ietf.org/html/rfc2516#section-5.3 , but BNGBlasted does not use Service-name tags.

**Comment by GIC-de** [comment]
This should be fixed in dev branch. Please verify and close.

**Comment by DmitriyEshenko** [comment]
@GIC-de , thank you. All work as expected!
