### ISSUE TITLE
Support for different IP's for different traffic streams to differentiate each of the destination servers

### ISSUE THREAD

**Issue by DharmendraShetty** [rtbrick/bngblaster#135]
**Describe the bug**
We need the option of changing different IP's to different streams while defining different traffic streams.

Considering one example:
1. For L2TP Tunneled Data Traffic(Multiple Traffic Streams) to be sent to different destinations, we need an option to specify the 
destination ipv4/ipv6 address for each stream. 

**To Reproduce**
NA

Version (`bngblaster -v`):
bngblaster -v
Version: 0.8.8
Compiler: GNU (7.5.0)
IO Modes: packet_mmap_raw (default), packet_mmap, raw

JSON configuration:
Sample JSON File:
--------------------------
{
  "interfaces": {
      "tx-interval": 1,
      "rx-interval": 1,
      "io-slots": 4096,
      "network": [
          {
              "interface": "SN-10-S1",
              "address": "[80.156.101.2/30](http://80.156.101.2/30)",
              "gateway": "80.156.101.1",
              "isis-instance-id": 1,
              "isis-level": 1
          }
      ],
      "access": [
      {
          "interface": "SN-7-L1",
          "outer-vlan-min": 128,
          "outer-vlan-max": 4094,
          "inner-vlan-min": 7,
          "inner-vlan-max": 7,
    "stream-group-id": 1,
          "network-interface": "SN-10-S1"
      },
      {
          "interface": "SN-12-L1",
          "outer-vlan-min": 128,
          "outer-vlan-max": 4094,
          "inner-vlan-min": 7,
          "inner-vlan-max": 7,
    "stream-group-id": 1,
          "network-interface": "SN-10-S1"
      }
   ]  
  },
  "sessions": {
      "count": 1,
      "session-time": 0,
      "max-outstanding": 800,
      "start-rate": 400,
      "stop-rate": 400,
      "start-delay": 30
  },
  "pppoe": {
      "reconnect": true,
      "discovery-timeout": 3,
      "discovery-retry": 10,
      "host-uniq": true,
      "vlan-priority": 6
  },
  "ppp": {
      "mru": 1492,
      "authentication": {
          "username": "[l2tp4@t-online.de](mailto:l2tp4@t-online.de)",
          "password": "test",
          "timeout": 1,
          "retry": 60
      }
  },
  "dhcpv6": {
      "enable": false
  },
  "access-line": {
      "agent-remote-id": "DEU.RTBRICK.{session-global}",
      "agent-circuit-id": "[0.0.0.0/0.0.0.0](http://0.0.0.0/0.0.0.0) eth 0:{session-global}"
  },
  "streams": [
      {
          "name": "BestEffort",
          "stream-group-id": 1,
          "type": "ipv4",
          "direction": "both",
          "priority": 128,
          "vlan-priority": 3,
          "length": 1000,
          "bps": 1000000
      },
      {
          "name": "LL",
          "stream-group-id": 1,
          "type": "ipv4",
          "direction": "both",
          "priority": 64,
          "vlan-priority": 4,
          "network-ipv4-address": "87.141.133.1",
          "length": 1000,
          "bps": 1000000
      },
      {
          "name": "LD",
          "stream-group-id": 1,
          "type": "ipv4",
          "direction": "both",
          "priority": 184,
          "vlan-priority": 5,
          "network-ipv4-address": "80.157.240.1",
          "length": 1000,
          "bps": 1000000
      },
      {
          "name": "VO",
          "stream-group-id": 1,
          "type": "ipv4",
          "direction": "both",
          "priority": 224,
          "vlan-priority": 6,
          "network-ipv4-address": "217.0.16.1",
          "length": 256,
          "bps": 1000000
      }
  ],
  "l2tp-server": [
      {
          "name": "LNS1",
          "address": "100.0.0.11",
          "secret": "test1",
          "receive-window-size": 64,
          "data-length": false,
          "data-offset": false,
          "data-control-priority": true
      },
      {
          "name": "LNS2",
          "address": "100.0.0.12",
          "secret": "test2",
          "receive-window-size": 64,
          "data-length": true,
          "data-offset": false,
          "data-control-priority": true
      },
      {
          "name": "LNS3",
          "address": "100.0.0.13",
          "secret": "test3",
          "receive-window-size": 64,
          "data-length": false,
          "data-offset": true,
          "data-control-priority": true
      },
      {
          "name": "LNS4",
          "address": "100.0.0.14",
          "secret": "test4",
          "receive-window-size": 64,
          "data-length": true,
          "data-offset": true,
          "data-control-priority": true
      },
      {
          "name": "LNS5",
          "address": "100.0.0.15",
          "secret": "test5",
          "receive-window-size": 64,
          "data-control-priority": true
      },
      {
          "name": "LNS6",
          "address": "100.0.0.16",
          "secret": "test6",
          "receive-window-size": 64,
          "data-control-priority": true
      },
      {
          "name": "LNS7",
          "address": "100.0.0.17",
          "secret": "test7",
          "receive-window-size": 64,
          "data-control-priority": true
      },
      {
          "name": "LNS8",
          "address": "100.0.0.18",
          "secret": "test8",
          "receive-window-size": 64,
          "data-control-priority": true
      },
      {
          "name": "LNS9",
          "address": "100.0.0.19",
          "secret": "test9",
          "receive-window-size": 64,
          "data-control-priority": true
      },
      {
          "name": "LNS10",
          "address": "100.0.0.20",
          "secret": "test10",
          "receive-window-size": 64,
          "data-control-priority": true
      },
      {
          "name": "LNS11",
          "address": "100.0.0.21",
          "secret": "test11",
          "receive-window-size": 64,
          "data-control-priority": true
      },
      {
          "name": "LNS12",
          "address": "100.0.0.22",
          "secret": "test12",
          "receive-window-size": 64,
          "data-control-priority": true
      },
      {
          "name": "LNS13",
          "address": "100.0.0.23",
          "secret": "test13",
          "receive-window-size": 64,
          "data-control-priority": true
      },
      {
          "name": "LNS14",
          "address": "100.0.0.24",
          "secret": "test14",
          "receive-window-size": 64,
          "data-control-priority": true
      },
      {
          "name": "LNS15",
          "address": "100.0.0.25",
          "secret": "test15",
          "receive-window-size": 64,
          "data-control-priority": true
      },
      {
          "name": "LNS16",
          "address": "100.0.0.26",
          "secret": "test16",
          "receive-window-size": 64,
          "data-control-priority": true
      },
      {
          "name": "LNS17",
          "address": "100.0.0.27",
          "secret": "test17",
          "receive-window-size": 64,
          "data-control-priority": true
      },
      {
          "name": "LNS18",
          "address": "100.0.0.28",
          "secret": "test18",
          "receive-window-size": 64,
          "data-control-priority": true
      },
      {
          "name": "LNS19",
          "address": "100.0.0.29",
          "secret": "test19",
          "receive-window-size": 64,
          "data-control-priority": true
      },
      {
          "name": "LNS20",
          "address": "100.0.0.30",
          "secret": "test20",
          "receive-window-size": 64,
          "data-control-priority": true
      },
      {
          "name": "LNS21",
          "address": "100.0.0.31",
          "secret": "test21",
          "receive-window-size": 64,
          "data-control-priority": true
      },
      {
          "name": "LNS22",
          "address": "100.0.0.32",
          "secret": "test22",
          "receive-window-size": 64,
          "data-control-priority": true
      },
      {
          "name": "LNS23",
          "address": "100.0.0.33",
          "secret": "test23",
          "receive-window-size": 64,
          "data-control-priority": true
      },
      {
          "name": "LNS24",
          "address": "100.0.0.34",
          "secret": "test24",
          "receive-window-size": 64,
          "data-control-priority": true
      },
      {
          "name": "LNS25",
          "address": "100.0.0.35",
          "secret": "test25",
          "receive-window-size": 64,
          "data-control-priority": true
      },
      {
          "name": "LNS26",
          "address": "100.0.0.36",
          "secret": "test26",
          "receive-window-size": 64,
          "data-control-priority": true
      },
      {
          "name": "LNS27",
          "address": "100.0.0.37",
          "secret": "test27",
          "receive-window-size": 64,
          "data-control-priority": true
      },
      {
          "name": "LNS28",
          "address": "100.0.0.38",
          "secret": "test28",
          "receive-window-size": 64,
          "data-control-priority": true
      },
      {
          "name": "LNS29",
          "address": "100.0.0.39",
          "secret": "test29",
          "receive-window-size": 64,
          "data-control-priority": true
      },
      {
          "name": "LNS30",
          "address": "100.0.0.40",
          "secret": "test30",
          "receive-window-size": 64,
          "data-control-priority": true
      }
  ],
  "isis": [
      {
          "instance-id": 1,
          "area": [
              "49.0204/24"
          ],
          "system-id": "0204.0000.0001",
          "router-id": "80.156.101.201",
          "hostname": "BBL1",
          "hello-padding": true,
          "sr-base": 100000,
          "sr-range": 36000,
          "sr-node-sid": 30001,
          "level1-auth-key": "Adams",
          "level1-auth-type": "md5",
          "teardown-time": 30,
          "external": {
              "mrt-file": "/home/supervisor/isis.mrt",
              "connections": [
                  {
                      "system-id": "0204.0000.0003",
                      "l1-metric": 10
                  }
              ]
          }
      },
      {
          "instance-id": 2,
          "area": [
              "49.0204/24"
          ],
          "system-id": "0204.0000.0002",
          "router-id": "80.156.101.202",
          "hostname": "BBL2",
          "hello-padding": true,
          "sr-base": 100000,
          "sr-range": 36000,
          "sr-node-sid": 30002,
          "level1-auth-key": "Adams",
          "level1-auth-type": "md5",
          "teardown-time": 30,
          "external": {
              "mrt-file": "/home/supervisor/isis.mrt",
              "connections": [
                  {
                      "system-id": "0204.0000.0004",
                      "l1-metric": 10
                  }
              ]
          }
      }
  ],
  "bgp": [
      {
          "__comment__": "S1-RR-IPv4-A",
          "network-interface": "SN-10-S1",
          "local-ipv4-address": "62.225.16.180",
          "peer-ipv4-address": "62.225.21.144",
          "raw-update-file": "/home/supervisor/ipv4-min.bgp",
          "local-as": 3320,
          "peer-as": 3320
      },
      {
          "__comment__": "S1-RR-IPv6-A",
          "network-interface": "SN-10-S1",
          "local-ipv4-address": "62.225.16.181",
          "peer-ipv4-address": "62.225.21.144",
          "raw-update-file": "/home/supervisor/ipv6-min.bgp",
          "local-as": 3320,
          "peer-as": 3320
      },
      {
          "__comment__": "S1-RR-IPv4-B",
          "network-interface": "SN-10-S1",
          "local-ipv4-address": "62.225.16.183",
          "peer-ipv4-address": "62.225.21.144",
          "raw-update-file": "/home/supervisor/ipv4-min.bgp",
          "local-as": 3320,
          "peer-as": 3320
      },
      {
          "__comment__": "S1-RR-IPv6-B",
          "network-interface": "SN-10-S1",
          "local-ipv4-address": "62.225.16.184",
          "peer-ipv4-address": "62.225.21.144",
          "raw-update-file": "/home/supervisor/ipv6-min.bgp",
          "local-as": 3320,
          "peer-as": 3320
      }
  ]
}

NA

**Expected behavior**

NA
**Screenshots**

NA
**Additional context**

NA

**Comment by GIC-de** [comment]
Fixed!
