### ISSUE TITLE
BGP Update Python script is generating the JSON streams with wrong parameter

### ISSUE THREAD

**Issue by PraveenM94** [rtbrick/bngblaster#143]
**Description**
BGP Update Python script is generating the JSON streams with destination-ipv4-address instead of network-ipv4-address. Because of this bi directional traffic validation is not working as expected. 
Eg : 
Stream generated using bgpupdate
{
            "name": "77.1.0.0/24",
            "direction": "both",
            "pps": 100.0,
            "threaded": true,
            "thread-group": 1,
            "type": "ipv4",
            "destination-ipv4-address": "77.1.0.1",
            "stream-group-id": 1
        },
        {
            "name": "77.1.1.0/24",
            "direction": "both",
            "pps": 100.0,
            "threaded": true,
            "thread-group": 2,
            "type": "ipv4",
            "destination-ipv4-address": "77.1.1.1",
            "stream-group-id": 1
        },
        {
            "name": "77.1.2.0/24",
            "direction": "both",
            "pps": 100.0,
            "threaded": true,
            "thread-group": 3,
            "type": "ipv4",
            "destination-ipv4-address": "77.1.2.1",
            "stream-group-id": 1
        },

With this, upstream traffic sent via access interface is working fine - source IP is Subscriber IP and destination IP is [77.1.0.1/77.1.1.1] but for downstream traffic sent via network interface - source IP is network interface IP and destination IP is [77.1.0.1/77.1.1.1] - because of this downstream traffic comes to node via network interface and goes back again via network interface without going to access interface - ideally source IP should be [77.1.0.1/77.1.1.1] and destination IP should be Subscriber IP.

**To Reproduce**

Version: 0.8.8
Compiler: GNU (7.5.0)
IO Modes: packet_mmap_raw (default), packet_mmap, raw

bgpupdate -f ipv4_prefixes.bgp -a 1000 -n 131.0.0.2 -N 1 -p 77.1.0.0/24 -P 1000 -s streams.json --stream-group-id 1 --stream-pps 100 --stream-threads 4 --stream-direction both

**Expected behavior**

{
            "name": "77.1.0.0/24",
            "direction": "both",
            "pps": 100.0,
            "threaded": true,
            "thread-group": 1,
            "type": "ipv4",
            "network-ipv4-address": "77.1.0.1",
            "stream-group-id": 1
        },
        {
            "name": "77.1.1.0/24",
            "direction": "both",
            "pps": 100.0,
            "threaded": true,
            "thread-group": 2,
            "type": "ipv4",
            "network-ipv4-address": "77.1.1.1",
            "stream-group-id": 1
        },
        {
            "name": "77.1.2.0/24",
            "direction": "both",
            "pps": 100.0,
            "threaded": true,
            "thread-group": 3,
            "type": "ipv4",
            "network-ipv4-address": "77.1.2.1",
            "stream-group-id": 1
        },

**Comment by GIC-de** [comment]
@PraveenM94 please verify if fix is okay (https://github.com/rtbrick/bngblaster/blob/dev/code/bgpupdate)
