### ISSUE TITLE
Support incremental/decremental login/logout of subscribers respectively

### ISSUE THREAD

**Issue by DharmendraShetty** [rtbrick/bngblaster#146]
Description:
Suppose:
(i) 1K Subscribers loggedin, we need to further bring up 4K more subscribers in addition.
(ii)We have brought up 5K Subscribers, but we need to logout only 1K subscribers in that.
In this case we say incremental login of subcribers or decremental logout of subscribers.
We need this support.

Suggestion/Solution:
Grouping of Subscribers. 
So that incremental addition of subscribers will not disturb/logout/terminate existing subscribers.
Also decremental of subscribers in a specific group will not disturb/logout/terminate subcribers.

Additionally, if we need to terminate/logout just a single subcriber based on vlan option, this support also will be a good option

**Comment by GIC-de** [comment]
This is implemented with 0.8.12 using new `session-group-id`!

One or more access interface blocks can be grouped using the session-group-id, which allows applying some commands like session-start, session-stop or session-restart to all sessions belonging to the same group. The example below shows how to assign all even VLAN identifiers to session group 1 and all odd VLAN identifiers to session group 2.

```
{
    "access": [
        {
            "interface": "eth1",
            "type": "pppoe",
            "session-group-id": 1,
            "username": "even@rtbrick.com",
            "outer-vlan-min": 1000,
            "outer-vlan-max": 1998,
            "outer-vlan-step": 2,
            "inner-vlan": 7
        },
        {
            "interface": "eth1",
            "type": "pppoe",
            "session-group-id": 2,
            "username": "odd@rtbrick.com",
            "outer-vlan-min": 1001,
            "outer-vlan-max": 1999,
            "outer-vlan-step": 2,
            "inner-vlan": 7
        },
    ]
}
```
