### ISSUE TITLE
Support of Burst of some data pkts and then stop traffic 

### ISSUE THREAD

**Issue by DharmendraShetty** [rtbrick/bngblaster#147]
Description:Support of Burst of some data pkts and then stop traffic 
Suppose:
(i) Currently we have support of continuous traffic of fixed length packets.
But we need the support of say for example:
Send 1000 PPS till total packet count of 100000.

Expectation:
Exactly on the lines of IXIA traffic streams where we have support of burst traffic, we need the same support here.
It helps in Quality of Service tests.

Thanks,

**Comment by GIC-de** [comment]
https://rtbrick.github.io/bngblaster/streams.html
If you set `"max-packets": 1000` in the stream definition, then it will stop automatically after 1000 packets.  Is this what you are looking for?
