### ISSUE TITLE
Support for NETMAP framework, to support other Oses that Linux. 

### ISSUE THREAD

**Issue by tatuzemdp** [rtbrick/bngblaster#16]
Hi there, any change to allow netmap to be used for high speed access to NIC rings?

**Comment by GIC-de** [comment]
I already considered netmap as an good option which should also allow higher PPS compared to packet_mmap. Plan would be to support multiple IO modes like packet_mmap (default), netmap or DPDK. 

Which OS is interesting for you besides Linux (FreeBSD, Windows, ...)?

**Comment by tatuzemdp** [comment]
Hi there! For now just interested on FreeBSD...

**Comment by tatuzemdp** [comment]
If you want i can help, not really good at coding but at least some donation.

**Comment by GIC-de** [comment]
You can try initial draft with netmap support here:
https://github.com/rtbrick/bngblaster/tree/netmap

```
cd build
cmake -DBNGBLASTER_NETMAP=on -DBNGBLASTER_VERSION=netmap ..
```

Feedback welcome!

**Comment by GIC-de** [comment]
To enable netmap, the following needs to be added in config. 

```
{
    "interfaces": {
        "tx-interval": 1, 
        "rx-interval": 1,
        "io-mode": "netmap",
        "network": {
            "interface": "veth2",
            "address": "100.0.0.10",
            "gateway": "100.0.0.2"
        }
    }
}
```
The rx/tx interval is 5ms per default but you can lower the poll rate to 1ms to reach higher PPS values.

**Comment by tatuzemdp** [comment]
nice!!! Will try it tomorrow morning!CheerssantiOn 18 Mar 2021 20:05, Christian Giese ***@***.***> wrote:
You can try initial draft with netmap support here:
https://github.com/rtbrick/bngblaster/tree/netmap
cd build
cmake -DBNGBLASTER_NETMAP=on -DBNGBLASTER_VERSION=netmap ..

Feedback welcome!

**Comment by tatuzemdp** [comment]
Thanks a lot. I already prep the server. Will clone tonightSantiOn 18 Mar 2021 20:07, Christian Giese ***@***.***> wrote:
To enable netmap, the following needs to be added in config.
{
    "interfaces": {
        "tx-interval": 1, 
        "rx-interval": 1,
        "io-mode": "netmap",
        "network": {
            "interface": "veth2",
            "address": "100.0.0.10",
            "gateway": "100.0.0.2"
        }
    }
}

The rx/tx interval is 5ms per default but you can lower the poll rate to 1ms to reach higher PPS values.

**Comment by tatuzemdp** [comment]
Dear, Chris, hope you are doing fine.

I clone and tried to compile but having issues with libdict. going out 
now but will try to sort it later.

Basically libdict seems to be broken, hence removed from FreeBSD 6 
months ago (lucky me).

I will keep you posted.

Santi

**Comment by GIC-de** [comment]
You can build/install libdict manually from here:

https://github.com/rtbrick/libdict

**Comment by tatuzemdp** [comment]
Will do! Thanks for the pointer!On 20 Mar 2021 13:07, Christian Giese ***@***.***> wrote:
You can build/install libdict manually from here:
https://github.com/rtbrick/libdict

**Comment by tatuzemdp** [comment]
Hi Chris,

SO, libdict is now compile/installed and out of the way.

As expected, is complaining about linux/if_packet.h (just commented out 
to see where else it complain) and got issues with CIRCLEQ that is not 
part of sys/queue.h.

I will continue on later on, keep you posted.

Santi

**Comment by tatuzemdp** [comment]
Chris, will be it be enough to replace circularq with a STAILQ? 
-------- Original message --------From: Christian Giese ***@***.***> Date: 20/03/2021  13:07  (GMT+01:00) To: rtbrick/bngblaster ***@***.***> Cc: Santiago Martinez ***@***.***>, Author ***@***.***> Subject: Re: [rtbrick/bngblaster] Support for NETMAP framework, to support other Oses that Linux.  (#16) 
You can build/install libdict manually from here:
https://github.com/rtbrick/libdict

**Comment by GIC-de** [comment]
The BNG Blaster will officially support Linux only.
