### ISSUE TITLE
No DSCP/pBit value for PPP LCP

### ISSUE THREAD

**Issue by SoerenBusse** [rtbrick/bngblaster#179]
**Describe the bug**
BNGBlaster is sending PPP LCP packets in QoS Class Best-Effort instead of QoS Class 6, like a Juniper BNG does. This affects the access-side as well as the L2TP server side (what we're currently testing). It might also affect the A10-NSP PPP server, which we have not tested.

![image](https://user-images.githubusercontent.com/7796567/236273941-4cf6b643-fb85-43d8-a89d-2adab4569719.png)

Sadly, I haven't found an RFC which states what QoS class to use for PPP LCP packets. However, Deutsche Telekom requires the `LCP Echo Request` to be sent in QoS class 6 according to TR-112:
![image](https://user-images.githubusercontent.com/7796567/236271552-20801a12-9c76-4d4e-9e2b-4d2ffca3ba8d.png)

A Fritz!Box is sending all LCP packets in QoS class 6. All other in QoS class 0, while JunOS sends every PPP signaling packet in QoS class 6.
| Type  | QoS-Class  |
|---|--- |
| Discovery PADI  | 0  |
| Discovery PADR | 0  |
|  LCP Configuration Request | 6  |
|  LCP Configuration ACK | 6  |
|  LCP Discard Request | 6  |
|  PAP Authenticate-Request | 0  |
|  PAP Authenticate-Request | 0  |
|  IPCP Configuration Request | 6  |
|  LCP Termination Request | 6  |
|  LCP Echo Request | 6  |

Strangely, the TR-112 specification of using QoS class 6 contradicts the L2BSA specification by NGA-Forum which proposes to drop QoS class 6 completely: section 2.3.5.1
https://www.bundesnetzagentur.de/SharedDocs/Downloads/DE/Sachgebiete/Telekommunikation/Breitband/NGA_NGN/NGA-Forum/aktuelledokumente/L2_BSA_II_TechSpezifikation_V21_140601.pdf;jsessionid=1DD26F40218060943223E22091BA6035?__blob=publicationFile&v=3

Maybe it would be possible to implement a switch for enabling the one or the other behavior to test both cases?

**To Reproduce**

Version (`bngblaster -v`):

```
Version: DEV
Compiler: GNU (11.3.0)
GIT:
  REF: dev
  SHA: 1d3b7ccb5429ff7e976d5e5b4790e2ea0cec225c
IO Modes: packet_mmap_raw (default), packet_mmap, raw, dpdk
```

JSON configuration:
```json
{
{
  "interfaces": {
    "capture-include-streams": true,
    "tx-interval": 0.1,
    "network": {
      "interface": "enp1s0f1np1",
      "address": "10.189.214.2",
      "gateway": "10.189.214.1"
    },
    "access": [
      {
        "interface": "enp1s0f0np0",
        "outer-vlan-min": 109,
        "outer-vlan-max": 109,
        "inner-vlan-min": 7,
        "inner-vlan-max": 7,
        "qinq": true,
        "authentication-protocol": "CHAP",
        "stream-group-id": 1
      }
    ]
  },
  "pppoe": {
    "reconnect": true,
    "discovery-timeout": 3,
    "discovery-retry": 10
  },
  "ppp": {
    "mru": 1492,
    "authentication": {
      "username": "lacgfnw",
      "password": "password",
      "timeout": 1,
      "retry": 60
    },
    "lcp": {
      "conf-request-timeout": 5,
      "conf-request-retry": 30,
      "keepalive-interval": 30,
      "keepalive-retry": 3
    },
    "ipcp": {
      "enable": true
    },
    "ip6cp": {
      "enable": true
    }
  },
  "l2tp-server": [
    {
      "name": "LNS1",
      "address": "10.189.214.2",
      "secret": "bngblaster",
      "receive-window-size": 8
    }
  ],
  "streams": [
    {
      "stream-group-id": 1,
      "name": "Teststream",
      "type": "ipv4",
      "direction": "downstream",
      "pps": 100000,
      "length": 128
    },
    {
      "stream-group-id": 1,
      "name": "Teststream",
      "type": "ipv4",
      "direction": "upstream",
      "pps": 1000,
      "length": 128
    }
  ]
}
}
```

**Comment by GIC-de** [comment]
Have you tried to set [vlan-priority](https://rtbrick.github.io/bngblaster/configuration/index.html#pppoe): 
```json
{ "pppoe": { "vlan-priority": 6 } }
```

**Comment by GIC-de** [comment]
@SoerenBusse is the proposed solution using [vlan-priority](https://rtbrick.github.io/bngblaster/configuration/index.html#pppoe) working for you so that issue can be closed?

**Comment by SoerenBusse** [comment]
@GIC-de Sorry for the late reply. I've just tried it in an IP-BSA scenario using a LNS. While the packets are correctly marked on upstream to CS6, the LNS is not setting the DSCP value accordingly in downstream:
![image](https://github.com/rtbrick/bngblaster/assets/7796567/b6a7846d-e661-4884-9d63-6b1f9dc3316e)

![image](https://github.com/rtbrick/bngblaster/assets/7796567/826caea8-9feb-4f51-b316-7a6ff4d044b8)

**Comment by GIC-de** [comment]
For L2TP downstream, you could set the marking using the option `control-tos` and `data-control-tos`. 
https://rtbrick.github.io/bngblaster/configuration/index.html#l2tpv2-server-lns

**Comment by SoerenBusse** [comment]
Hi, these options work like a charm. Wasn't able to test it ealier :(
