### ISSUE TITLE
Not all IPoE clients are established if the outstanding value is set to a value equal to the number of clients

### ISSUE THREAD

**Issue by d1sl1ke** [rtbrick/bngblaster#186]
**Describe the bug**

Not all IPoE clients are established if the outstanding value is set to a value equal to the number of clients.

**To Reproduce**

Version (`bngblaster -v`):

```
Version: DEV
Compiler: GNU (11.3.0)
IO Modes: packet_mmap_raw (default), packet_mmap, raw, dpdk
```

JSON configuration:
```json
{
    "interfaces": {                                                                                                                                                                          
        "tx-interval": 0.1,                                                                                                                                                                  
        "rx-interval": 0.1,                                                                                                                                                                  
        "links": [                                                                                                                                                                           
            {                                                                                                                                                                                
                "interface": "0000:81:00.0",                                                                                                                                                 
                "io-mode": "dpdk",                                                                                                                                                           
                "rx-threads": 4,                                                                                                                                                             
                "rx-cpuset": [1,2,3,4],                                                                                                                                                      
                "tx-threads": 4,                                                                                                                                                             
                "tx-cpuset": [5,6,7,8]                                                                                                                                                       
            },                                                                                                                                                                               
            {                                                                                                                                                                                
                "interface": "0000:81:00.1",                                                                                                                                                 
                "io-mode": "dpdk",                                                                                                                                                           
                "rx-threads": 4,                                                                                                                                                             
                "rx-cpuset": [9,10,11,12],                                                                                                                                                   
                "tx-threads": 4,                                                                                                                                                             
                "tx-cpuset": [13,14,15,16]                                                                                                                                                   
            }                                                                                                                                                                                
        ],
        "access": [
            {
                "__comment__": "DHCP Client",
                 "interface": "0000:81:00.0",
                "type": "ipoe",
                "ipv6": false,
                "outer-vlan-min": 1100,
                "outer-vlan-max": 1113,
                "outer-vlan-step": 1,
                "inner-vlan-min": 1,
                "inner-vlan-max": 600,
                "inner-vlan-step": 1,
                "stream-group-id": 1
            },
            {
                "__comment__": "DHCP Client2",
                 "interface": "0000:81:00.1",
                "type": "ipoe",
                "ipv6": false,
                "outer-vlan-min": 1114,
                "outer-vlan-max": 1133,
                "outer-vlan-step": 1,
                "inner-vlan-min": 1,
                "inner-vlan-max": 600,
                "inner-vlan-step": 1,
                "stream-group-id": 1
            }
        ]
    },
    "sessions": {
        "count": 50,
        "max-outstanding": 5,
        "start-rate": 3200,
        "stop-rate": 3200,
        "iterate-vlan-outer": true,
        "autostart": true,
        "reconnect": false
    }
}
```

1. Generate IPoE clients
2. When `max-outstanding` is set to 5, clients are generated 5 by 5. It takes ~10s for current configuration
3. When `max-outstanding` is set to 50 for current configuration (or equal to clients number), clients are generated so fast (3k per ~2s), but established ~60-70% only (All DHCP clients are passed DORA (check a screenshot))

**Screenshots**

![image](https://github.com/rtbrick/bngblaster/assets/52015843/3d9a9555-d7f4-4053-a1bc-0f34a8a15411)
**Additional context**

**Comment by d1sl1ke** [comment]
For example 5k clients take 4s, but half of clients are established only (`"max-outstanding": 5000`)
![image](https://github.com/rtbrick/bngblaster/assets/52015843/a59275f0-e5c8-4af1-b482-60f4b83f88b8)

**Comment by d1sl1ke** [comment]
UPD:
Number of established clients can be increased when DHCP clients send another DHCP Request.

**Comment by d1sl1ke** [comment]
> Why did you select such a high start-rate? The start- and stop-rate should be typically around 200-400 sessions per second (default is 400). Ideally you would set the start-rate to twice the expected session setup rate and outstanding to twice the start-rate. 
> 
> A typical BNG is able to handle up to 200 sessions per second, so default 400 should be fine. 

I stress tested, and some thousands rps is correct value for BNG.
This behavior is the same if start-rate is equal to clients number. Doesn't matter: 50/50,100/100,10000/10000. ~70% are established after first DORA cycle, and increase in next DHCP Rrequests. And 100% are established after 4 requests cycle (2*lease-time).

It looks like last ACK packets dont analyzed to mark as established (all emulated clients received ACK).

**Comment by d1sl1ke** [comment]
And I suppose, that blaster does not send requests more than the number of clients. 50 only in my example

**Comment by GIC-de** [comment]
I guess it's not a DHCP issue in your case. You can see in the DHCPv4 progress bar that all your DHCPv4 sessions are established. But for a session to become established, the initial ARP requests must be successful as well. As soon as DHCP has finished, the emulated client tries to resolve the learned gateway via ARP request. The session is marked es established only if this has been successfully, because this is the state from where on the session is actually usable for the clients.

**Comment by d1sl1ke** [comment]
> I guess it's not a DHCP issue in your case. You can see in the DHCPv4 progress bar that all your DHCPv4 sessions are established. But for a session to become established, the initial ARP requests must be successful as well. As soon as DHCP has finished, the emulated client tries to resolve the learned gateway via ARP request. The session is marked es established only if this has been successfully, because this is the state from where on the session is actually usable for the clients.
> 
> You can press F1 to see protocol timeout stats, here ARP might be increasing.

Yes, thank you for help. One more question: can blaster generate TCP flow? Or UDP only?

**Comment by GIC-de** [comment]
Currently UDP only but TCP is already planned. Generic TCP support using lwIP (https://savannah.nongnu.org/projects/lwip/) is already included as required for protocols like BGP or LDP but currently not exposed to streams.

**Comment by d1sl1ke** [comment]
Okay, thank you so much! You can close this ticket.
