### ISSUE TITLE
Established remains at zero for DHCPv4 IPoE

### ISSUE THREAD

**Issue by vettamatt** [rtbrick/bngblaster#209]
**Describe the bug**

Established remains at zero for DHCPv4 IPoE, although ARP is succeeding.

**To Reproduce**

Version (`bngblaster -v`):

```
# bngblaster -v
Version: DEV
Compiler: GNU (11.4.0)
IO Modes: packet_mmap_raw (default), packet_mmap, raw
```

(Compiled from source yesterday using documented process, on Ubuntu 22.04)

JSON configuration:
```json
{
    "sessions": {
        "count": 1,
        "reconnect": true,
        "autostart": true,
        "start-delay": 2,
        "start-rate": 200,
        "stop-rate": 200,
        "max-outstanding": 20000
    },
    "interfaces": {
        "access": [
            {
                "__comment__": "DHCP Server",
                "interface": "ens19",
                "type": "ipoe",
                "vlan-mode": "1:1",
                "outer-vlan-min": 1001,
                "outer-vlan-max": 1002,
                "inner-vlan-min": 1000,
                "inner-vlan-max": 3000
            }
        ]
    },
    "access-line": {
        "agent-remote-id": "PROVIDER{session-global}",
        "agent-circuit-id": "PROVIDER{session-global}"
    },
    "ipoe": {
        "arp-interval": 20,
        "arp-timeout": 1
    },
    "dhcp": {
        "enable": true,
        "broadcast": true,
        "timeout": 5,
        "retry": 5,
        "access-line": true
    },
    "dhcpv6": {
        "enable": false
    }
}
```

1. Run `bngblaster -C dhcpv4.json --logging dhcp --interactive -S /root/bngblaster/bngblaster.sock`

**Expected behavior**

I expect the sessions to become established. BNG Blaster was stable with one outstanding session.

**Screenshots**

<img width="359" alt="BNGBlaster1" src="https://github.com/rtbrick/bngblaster/assets/115507223/66e6e542-89f0-46fb-8a35-8346e88309c3">
<img width="330" alt="BNGBlaster2" src="https://github.com/rtbrick/bngblaster/assets/115507223/3be84b5e-c472-4790-91fc-48e5d6e612e0">

**Additional context**

Issue [https://github.com/rtbrick/bngblaster/issues/186](186) is very similar, but in that scenario the problem was ARP.

Interface status:

```
# ip a show ens19
3: ens19: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9100 qdisc fq_codel state UP group default qlen 1000
    link/ether b2:3c:0b:be:73:c3 brd ff:ff:ff:ff:ff:ff
    altname enp0s19
```

Netplan config:

```
# This is the network config written by 'subiquity'
network:
  ethernets:
    ens18:
      dhcp4: true
    ens19:
      dhcp4: false
      dhcp6: false
      link-local: []
      mtu: 9100
  version: 2
```

**Comment by GIC-de** [comment]
It would be easier for me if you could provide a capture (start BNG Blaster with `-P test.pcap`) attached to this bug or via mail to bngblaster@rtbrick.com.

**Comment by vettamatt** [comment]
Thanks for your reply, pcap sent via email now.
