### ISSUE TITLE
CGNAT: Dynamically adding more Traffic flows for a group of active subscribers already with existing traffic flows

### ISSUE THREAD

**Issue by DharmendraShetty** [rtbrick/bngblaster#222]
Feature Enhancement:
Dynamically adding more Traffic flows for a group of active subscribers already with existing traffic flows

Description:
**************
Suppose we have a scaled subscribers say 1000 Subscribers, and 100 bidirectional traffic flows are going on(TX/RX)
Dynamically on these 1000 subscribers with 100 bidirectional traffic flows, we need to add 500 more traffic flows.

Usually, on the fly adding of udp/tcp flows for the Active subscribers would be helpful to test real time scenarios.

Thanks,
Dharmendra

**Comment by GIC-de** [comment]
Fixed with version 0.8.36!
