### ISSUE TITLE
Bngblaster session is not getting terminated with either Ctrl+c or 'terminate' command during longevity test   

### ISSUE THREAD

**Issue by bhishma-acharya** [rtbrick/bngblaster#26]
**Describe the bug**
Bngblaster session is running from past ~10hrs and When ctrl+c signal is sent to the running bngblaster session, session is not getting terminated.
Same results, when I used command 'terminate' using cli.
------------------------------------------------------------------------------------------
[00:38][Bhishma@srv2:~/bngblaster][main*]$date;sudo bngblaster -C ../srv2_zap_test_config_4.json -S test.socket;date
Fri Apr  9 00:38:42 IST 2021
Apr 09 00:38:43.065249 Getting MAC address 3c:fd:fe:c2:06:48 for interface ens2f0
Apr 09 00:38:43.137562 Add interface ens2f0
Apr 09 00:38:43.209226 Getting MAC address 3c:fd:fe:c2:06:49 for interface ens2f1
Apr 09 00:38:43.289576 Add interface ens2f1
Apr 09 00:38:43.292030 Opened control socket test.socket
Apr 09 00:38:44.403417 ALL SESSIONS ESTABLISHED
^CApr 09 09:10:02.636662 Received signal Interrupt (2), initiating teardown

^CApr 09 09:13:13.806373 Received signal Interrupt (2), initiating teardown
Apr 09 09:21:43.816481 Teardown request

Apr 09 09:26:44.015730 Teardown request

Apr 09 09:26:55.626354 Teardown request

------------------------------------------------------------------------------------------
Bhishma@srv2:~/bngblaster$ sudo ./cli.py test.socket terminate
{
    "status": "ok",
    "code": 200,
    "message": "terminate all sessions"
}
Bhishma@srv2:~/bngblaster$ sudo ./cli.py test.socket terminate
{
    "status": "ok",
    "code": 200,
    "message": "terminate all sessions"
}
Bhishma@srv2:~/bngblaster$ sudo ./cli.py test.socket session-info
{
    "status": "warning",
    "code": 404,
    "message": "session not found"
}
Bhishma@srv2:~/bngblaster$
 

**To Reproduce**

Version (`bngblaster -v`): 

```
```

JSON configuration:
```json
{
}
``` 

1. This is a longevity test

**Expected behavior**
bngblaster session must have terminated.

**Screenshots**

**Additional context**

**Comment by GIC-de** [comment]
Which version was used?

**Comment by GIC-de** [comment]
Not reproducible.
