### ISSUE TITLE
Sessions established count is zero when we bring up only with dhcpv6 and Traffic not starting

### ISSUE THREAD

**Issue by kishore3739** [rtbrick/bngblaster#33]
**Describe the bug**
Sessions established count is zero when we bring up only with dhcpv6 and Traffic not starting
Sessions established count is zero when we bring up only with dhcpv6 and Traffic not starting
**To Reproduce**
1] Bring up only ipoe dhcpv6
Version (`bngblaster -v`): 
Latest bngblaster Version

```
```

JSON configuration:
```json
{
    "interfaces": {
        "tx-interval": 1,
        "rx-interval": 1,
        "io-slots": 4096,
        "network": {
            "interface": "br-spine1-0",
            "address": "131.0.0.2",
            "gateway": "131.0.0.1",
            "address-ipv6": "fc66:1337:7331::2",
            "gateway-ipv6": "fc66:1337:7331::1"
        },	
        "access": [
        {
            "interface": "leaf1-1",
            "type": "ipoe",
            "outer-vlan-min": 1201,
            "outer-vlan-max": 1300,
            "inner-vlan-min": 1001,
            "inner-vlan-max": 1100
        }
     ]  
    },
    "sessions": {
        "count": 5,
        "session-time": 0,
        "max-outstanding": 800,
        "start-rate": 400,
        "stop-rate": 100
    },
    "access-line": {
        "agent-remote-id": "DEU.RTBRICK.{session-global}",
        "agent-circuit-id": "0.0.0.0/0.0.0.0 eth 0:{session-global}",
        "rate-up": 2000,
        "rate-down": 16384,
        "dsl-type": 5
    },
    "dhcp": {
        "enable": false
    },
    "dhcpv6": {
        "enable": true
    },
    "session-traffic": {
        "autostart": true,
        "ipv6-pps": 1,
        "ipv6pd-pps": 1
    }
}

``` 

1. ...

**Expected behavior**
Sessions established count should not be zero and traffic should work

**Screenshots**

**Additional context**

**Comment by kishore3739** [comment]
Adding bngblaster data:
F1: Select View  F7/F8: Start/Stop Traffic  F9: Terminate Sessions
Left/Right: Select Interface

      ____   __   ____         _        __                                  ,/
     / __ \ / /_ / __ ) _____ (_)_____ / /__                              ,'/
    / /_/ // __// __  |/ ___// // ___// //_/                            ,' /
   / _, _// /_ / /_/ // /   / // /__ / ,<                             ,'  /_____,
  /_/ |_| \__//_____//_/   /_/ \___//_/|_|                          .'____    ,'
      ____   _   _  ______   ____   _               _                    /  ,'
     / __ ) / | / // ____/  / __ ) / /____ _ _____ / /_ ___   ____      / ,'
    / __  |/  |/ // / __   / __  |/ // __ `// ___// __// _ \ / ___/    /,'
   / /_/ // /|  // /_/ /  / /_/ // // /_/ /(__  )/ /_ /  __// /       /
  /_____//_/ |_/ \____/  /_____//_/ \__,_//____/ \__/ \___//_/


Sessions               5 (0 PPPoE / 5 IPoE)
  Established          0 [                                                            ]
  Outstanding          0 [                                                            ]
  Terminated           0 [                                                            ]
  Setup Time           0 ms
  Setup Rate        0.00 CPS (MIN: 0.00 AVG: 0.00 MAX: 0.00)
  Flapped              0

DHCPv6
  Sessions             5
  Established          5 [############################################################]

Network Interface ( br-spine1-0 )
  Tx Packets                         3 |      0 PPS          0 Kbps
  Rx Packets                        13 |      0 PPS          0 Kbps
  Tx Session Packets                 0 |      0 PPS
  Rx Session Packets                 0 |      0 PPS          0 Loss
  Tx Session Packets IPv6            0 |      0 PPS

**Comment by GIC-de** [comment]
Fixed in latest development build targeted for release 0.5.4.
