### ISSUE TITLE
DHCPv6 - Is dhcpv6 working on v5.5?

### ISSUE THREAD

**Issue by tatuzemdp** [rtbrick/bngblaster#40]
[bng.txt](https://github.com/rtbrick/bngblaster/files/7114408/bng.txt)
Hi there, 
Quick question, we have a bng here configured with Dual-stack PPPoE. BNG configuration is working as we some other test clients with v4/v6 connected. Bngblaster, is also working but only for v4.  DHCPv6 seems to be stuck in init, but doing a packet capture on the host I cannot see any v6 request generated.

Also, seems that debug/logging not working (or I'm doing something wrong, most probably).

The release we are using is 5.5, using the debian pre-build package.

Version: 0.5.5
IO Modes: packet_mmap_raw (default), packet_mmap, raw

`root@bng-tg1:/home/smartinez# bngblaster-cli /var/run/bng session-info session-id 1
{
    "status": "ok",
    "code": 200,
    "session-info": {
        "type": "pppoe",
        "session-id": 1,
        "session-state": "Established",
        "interface": "enp0s5f2",
        "outer-vlan": 100,
        "inner-vlan": 0,
        "mac": "02:00:00:00:00:01",
        "username": "test",
        "lcp-state": "Opened",
        "ipcp-state": "Opened",
        "ip6cp-state": "Opened",
        "ipv4-address": "203.0.13.83",
        "dhcpv6-state": "Init",
        "tx-packets": 16,
        "rx-packets": 13,
        "rx-fragmented-packets": 0
    }
}
`

**Comment by GIC-de** [comment]
Could you share the corresponding JSON config file? You can hide/remove all interface name, username, password fields. 

Currently DHCPv6 starts as soon as ICMPv6 router-advertisement is received but also only if other config flag is set!

**Comment by tatuzemdp** [comment]
Hi there! its attached, nothing to hide, its just from the lab facility.

**Comment by tatuzemdp** [comment]
that explains why is not kicking in.

**Comment by tatuzemdp** [comment]
Its working now, just modify the BNG config to satisfy the IF statements. Thanks a lot for the quick reply. Will close the ticket.

**Comment by tatuzemdp** [comment]
Closing the tickets and bngblaster work as expected (great). Just make sure your bng is sending RA. 

On our case we have some other CPE just initiating DHCPV6 without caring if RA are present or not. 

Regarding BNGB, we have 32K session per VM in N:1. If working with  juniper bng's, just add make sure you have something like to ( not required to be exactly the same, but that on the current setup) :

set dynamic-profiles PPPOE_PROFILE protocols router-advertisement interface "$junos-interface-name" managed-configuration
set dynamic-profiles PPPOE_PROFILE protocols router-advertisement interface "$junos-interface-name" prefix $junos-ipv6-ndra-prefix

**Comment by GIC-de** [comment]
Thanks a lot for this feedback which is very valuable. 

I would propose to use `other-stateful-configuration` instead of `managed-configuration`.
 
```
set dynamic-profiles PPPOE_PROFILE protocols router-advertisement interface "$junos-interface-name" other-stateful-configuration
```
https://www.juniper.net/documentation/us/en/software/junos/neighbor-discovery/topics/ref/statement/other-stateful-configuration-edit-protocols-router-advertisement.html

**Comment by tatuzemdp** [comment]
Hi Chris, your are welcome, great support by the way!

Indeed we also tested bngb with other-state... and no issues at all.

Santi
