### ISSUE TITLE
DHCPv6 LDRA behaviour

### ISSUE THREAD

**Issue by mancz** [rtbrick/bngblaster#96]
Currently it is possible to set the `interface-id` and `remote-id` via `access-line` for DHCPv6, but this results in adding option17/38 to the normal DHCPv6 packet.

I would think that in most situations option17/38 are added by an LDRA-agent, and the original DHCP-request is encapsulated in the `relay-message` option (option9). Currently our Juniper BRAS is rejecting the `SOLICIT`s, because the packet is not constructed as a non relay-packet.
Reference: https://datatracker.ietf.org/doc/html/rfc6221

In our set-up our L2 switches act as LDRA agent and add option17/18 information, which works fine. Unfortunately we currently cannot mimic this behaviour with bngblaster.

Would it be possible to add DHCPv6 LDRA-emulation to BNGblaster?

**Comment by GIC-de** [comment]
Your request is about support DHCPv6 LDRA, meaning that Blaster sends packets emulating the client and the LDRA agent? So packets send by BNG Blaster look like those send by LDRA agent?

Could you provide some PCAP example?

**Comment by mancz** [comment]
Sorry for the late reply, we had some issues to reproduce.

Attached 2 PCAPs. `bng.pcap` is captured on the access-interface of the bng, `client.pcap` is captured on the client interface. The switch in between of the client and bng is configured with LDRA.
[bngblaster-96.tar.gz](https://github.com/rtbrick/bngblaster/files/9299559/bngblaster-96.tar.gz)

**Comment by GIC-de** [comment]
Sorry for lates response but working on this issue was delayed by the massive rework for version 0.8. I will try to address this as soon as possible. Because I'm unable to test this locally, I would push this to a dedicated feature branch and ask you to verify once before release.

**Comment by GIC-de** [comment]
I will implement this as part of the following changes:
https://github.com/rtbrick/bngblaster/pull/125

I already added a simple option to optionally disable the access line attributes for DHCPv4/6.

**Comment by Jonix71** [comment]
We also run Juniper MX as BNG and need this feature. It would be greate if BNG Blaster could emulate LDRA.  If you need more capture files just let me know.

**Comment by GIC-de** [comment]
I will start to work on LDRA support today. Maybe will have first draft by tomorrow.

**Comment by GIC-de** [comment]
Please check: https://github.com/rtbrick/bngblaster/pull/164

**Comment by GIC-de** [comment]
Please verify/check with `0.8.17`!

**Comment by Jonix71** [comment]
root@telenor-ThinkPad-T460:~# bngblaster -v
Version: 0.8.17
Compiler: GNU (11.3.0)
IO Modes: packet_mmap_raw (default), packet_mmap, raw

Works with LDRA towards Juniper MX.

Thx

**Comment by mancz** [comment]
Works on our end too. 
Thanks!
